name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Bazel
      uses: bazel-contrib/setup-bazel@0.8.5
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/WORKSPACE', '**/MODULE.bazel', '**/*.bzl') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
    - name: Build
      run: bazel build //... --config=release
    - name: Test
      run: bazel test //...
    - name: Bundle plugins
      run: bazel build //simple_amplifier:bundle --config=release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugin-${{ matrix.os }}
        path: bazel-bin/simple_amplifier/
